dependencies:
  # - name: neo4j-community
  #   version: 1.1.0
  #   repository: https://equinor.github.io/helm-charts/charts/
  #   condition: neo4j.enabled
  - name: elasticsearch
    version: 21.2.6
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
